### ISSUE TITLE
When re-opening and re-building content repos, getting 409 errors

### ISSUE THREAD

**Issue by annegentle** [deconst/client#38] opened 2015-09-22 13:31 UTC
When the deconst client is running, and all the content repo listings get done, the client can go into this loop where I get these errors:
Error: HTTP code is 409 which indicates error: undefined - Conflict. The name "preparer-control-3" is already in use by container 9398642eba94. You have to delete (or rename) that container to be able to reuse that name.

I can still get to the local site but want to report the error prior to demoing this in Austin. 

Here are some of the inspections I've done:

$ docker-machine ls
NAME             ACTIVE   DRIVER       STATE     URL                         SWARM
deconst-client   \*        virtualbox   Running   tcp://192.168.99.100:2376  
default                   virtualbox   Stopped    

$ docker ps -a
CONTAINER ID        IMAGE                                    COMMAND                  CREATED              STATUS                      PORTS                     NAMES
51576f74e5aa        quay.io/deconst/preparer-asset:latest    "/usr/src/app/script/"   About a minute ago   Exited (0) 55 seconds ago                             preparer-control-3
0aa2c3a1a9df        quay.io/deconst/preparer-asset:latest    "/usr/src/app/script/"   About a minute ago   Exited (0) 55 seconds ago                             preparer-control-5
389d944dcbcb        quay.io/deconst/preparer-asset:latest    "/usr/src/app/script/"   About a minute ago   Exited (0) 58 seconds ago                             preparer-control-4
78128d1a10e1        quay.io/deconst/preparer-jekyll:latest   "ruby -I/usr/src/app/"   4 minutes ago        Exited (0) 2 minutes ago                              preparer-content-3
5750c2f0ea13        quay.io/deconst/preparer-sphinx:latest   "deconst-preparer-sph"   4 minutes ago        Exited (0) 4 minutes ago                              preparer-content-5
7792043c6d2c        quay.io/deconst/preparer-sphinx:latest   "deconst-preparer-sph"   4 minutes ago        Exited (0) 4 minutes ago                              preparer-content-4
eafb20ed1303        quay.io/deconst/presenter:latest         "/bin/sh -c 'chown -R"   5 minutes ago        Up 5 minutes                0.0.0.0:32773->8080/tcp   presenter-3
09755893df9d        quay.io/deconst/presenter:latest         "/bin/sh -c 'chown -R"   5 minutes ago        Up 5 minutes                0.0.0.0:32772->8080/tcp   presenter-5
5ccead431ec7        quay.io/deconst/presenter:latest         "/bin/sh -c 'chown -R"   5 minutes ago        Up 5 minutes                0.0.0.0:32771->8080/tcp   presenter-4
d6545d94e0b5        quay.io/deconst/content-service:latest   "npm start"              5 minutes ago        Up 5 minutes                0.0.0.0:32770->8080/tcp   content-5
80b08b7bc550        quay.io/deconst/content-service:latest   "npm start"              5 minutes ago        Up 5 minutes                0.0.0.0:32769->8080/tcp   content-3
e85583585540        quay.io/deconst/content-service:latest   "npm start"              5 minutes ago        Up 5 minutes                0.0.0.0:32768->8080/tcp   content-4

**Comment by smashwilson** [comment] 2015-09-22 13:32
This is a duplicate of deconst/deconst-docs#167.

**Closed as completed** 2016-03-27 14:09 UTC
