### ISSUE TITLE
Getting Warning: Unresponsive script when viewing clbs singlehtml page with deconst

### ISSUE THREAD

**Issue by masthalter** [deconst/client#31] opened 2015-09-15 18:29 UTC
I receive the following message when running the deconst client to view the clbs singlehtml page.

Warning: Unresponsive script
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://192.168.99.100:32769/__…e842eddbe6a0c3a6d098748e0d5.js:6

If I then click Stop script, the message goes away and the Nav in the left hand pane works fine.

**Comment by smashwilson** [comment] 2015-09-24 15:15
Duplicate of rackerlabs/nexus-control#169 and fixed by rackerlabs/nexus-control#175. Thanks for the report!

**Closed as completed by smashwilson** 2015-09-24 15:15 UTC
